## -*- encoding: utf-8 -*-
## This file (calc_1_labs.sagetex.sage) was *autogenerated* from calc_1_labs.tex with sagetex.sty version 2015/08/26 v3.0-92d9f7a.
import sagetex
_st_ = sagetex.SageTeXProcessor('calc_1_labs', version='2015/08/26 v3.0-92d9f7a', version_check=True)
