## -*- encoding: utf-8 -*-
## This file (2017-10-16-151432.sagetex.sage) was *autogenerated* from 2017-10-16-151432.tex with sagetex.sty version 2015/08/26 v3.0-92d9f7a.
import sagetex
_st_ = sagetex.SageTeXProcessor('2017-10-16-151432', version='2015/08/26 v3.0-92d9f7a', version_check=True)
_st_.endofdoc()
